# Generated by Django 5.1.2 on 2024-10-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=200)),
                ('book_description', models.CharField(max_length=255)),
                ('book_category', models.CharField(max_length=100)),
                ('book_price', models.IntegerField()),
                ('book_image', models.ImageField(upload_to='images/')),
                ('book_pages', models.IntegerField()),
                ('book_copies', models.IntegerField()),
                ('book_publisher', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
